version: '3.4'

services:  
  database:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment:
      MSSQL_SA_PASSWORD: tgX*6YdePuk*Nz
      ACCEPT_EULA: Y
      MSSQL_PID: Developer
    volumes:
      - mssql_data:/var/opt/mssql

  personalaccountingbackend:
    image: ${DOCKER_REGISTRY-}personalaccountingbackend
    build:
      context: .
      dockerfile: PersonalAccountingBackend/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      SECRET: PutHereYourSecretKey
    #ports:
    #  - 80:80
    #  - 443:443
    depends_on:
      - database

  personalaccountingweb:
    image: ${DOCKER_REGISTRY-}personalaccountingweb
    build:
      context: .\PersonalAccountingWEB
      dockerfile: \Dockerfile
    depends_on:
      - personalaccountingbackend

  proxy:
    build:
      context: ./Proxy
      dockerfile: Dockerfile
    depends_on:
      - personalaccountingbackend
      - personalaccountingweb
    ports:
      - 80:80
      - 443:443
    
volumes:
  mssql_data: